### ISSUE TITLE
Issue with Motion Augmentation – Not Getting Expected Results

### ISSUE THREAD

**Issue by viki9146** [yahskapar/MA-rPPG-Video-Toolbox#12]
I’ve been following the steps in the README to augment motion in videos, but I'm not seeing the expected results. Even after carefully implementing all instructions, the output isn’t as anticipated.

Are there any additional hyperparameters or settings I should consider to improve the results?

**Comment by yahskapar** [comment]
Hi @viki9146,

Can you share more details as to what's going on - what exactly are you doing (e.g., what dataset are you augmenting, are you using the rPPG-Toolbox for evaluation, etc) and what results _are_ you expecting? Are you able to augment motion into rPPG videos (e.g., UBFC-rPPG) at the very least, or are you running into issues there itself?

By the way, please do note this repo and [the paper associated with it](https://arxiv.org/pdf/2303.12059) is specific to rPPG videos, which you could evaluate using tools such as the [rPPG-Toolbox](https://github.com/ubicomplab/rPPG-Toolbox).  Depending on your test data, you might also want to try the pre-trained models in the rPPG-Toolbox as an initial check on your test data (i.e., does testing with MAUBFC TS-CAN perform better than UBFC TS-CAN? If not, why not? Is there something else going on with the test data that makes the videos challenging?).

Best regards,

Akshay

**Comment by yahskapar** [comment]
Hi @viki9146,

I'll go ahead and close this given the lack of additional discussion or follow-up. Feel free to create a new issue or re-open this one if your questions or concerns persist though, I'm happy to try and help.
